config/webpack.demo.js
index.ts
src/app/filters/examples/filter-example.component.ts
src/app/filters/filter-event.ts
src/app/filters/filter-field.ts
src/app/filters/filter-fields.component.html
src/app/filters/filter-fields.component.ts
src/app/filters/filter-query.ts
src/app/filters/filter-results.component.html
src/app/filters/filter-results.component.ts
src/app/filters/filter.component.spec.ts
src/app/filters/filter.component.ts
src/app/filters/filter.ts
src/app/filters/filters.module.ts
src/app/toolbar/examples/toolbar-example.component.ts
src/app/toolbar/toolbar.component.html
src/app/toolbar/toolbar.component.scss
src/app/toolbar/toolbar.component.spec.ts
src/app/toolbar/toolbar.component.ts

Refactored the filter and toolbar for the Planner UI. Fixed a couple style bugs as well.
FYI, I was able to replace most of the HTML in planner's work item page and now have the filter, Move menu, and Add icon running in the toolbar. However, this required some changes.
The existing Angular PF implementation just didn't quite fit. For example, we're not displaying a filter count (because of infinite scrolling) and there is an Add button in the right-hand corner of the toolbar, which Angular PF doesn't provide a location for. The filter also needed the ability to use both IDs and display values based on planner's somewhat unique filters.

Refactor filter and toolbar (consumer) to accommodate planner

---

src/app/filters/filter-config.ts
src/app/filters/filter-fields.component.html
src/app/filters/filter-fields.component.ts
src/app/filters/filter-results.component.html
src/app/toolbar/examples/toolbar-example.component.ts

The filter's tooltip is cut off by planner's black header. This mod provides the ability to change the tooltip placement. Instead of being cut off on top, we can move the tool tip to the side.

Add tooltip placement for filter

---

src/app/treelist/treelist-item.component.html
src/app/treelist/treelist-item.component.scss
src/app/treelist/treelist.component.html

I moved a couple Patternfly styles (list-view-pf, list-group & list-group-item) from the planner UI to the tree list component.
We will want to use these Patternfly styles in other places with the tree list. This means there are far less tree list styles to override in planner and/or elsewhere.
Note this is one of two PRs. After this is merged, I'll create another PR for planner with the latest npm version number.

Moved Patternfly styles from planner to tree list

---

src/app/treelist/treelist-item.component.ts

When a row is selected, I want to obtain the underlying objects provided to tree list via the onSelect event. This would be useful in planner to get the WorkItem object associated with the row.

Provide a way to obtain the underlying objects

---

src/app/treelist/treelist-item.component.html
src/app/treelist/treelist-item.component.scss

The tree list is not displaying a selected row highlighting properly in planner. When the user hovers over a row, it should still appear selected. 
Somewhere in planner or PF, the "selected" selector is being overridden. Don't want to add a bunch of extra CSS to override this selector name in planner -- it already exists in treelist.

Changed name of selector to avoid inherited styling

---

src/app/filters/filter-fields.component.html

The unit tests are outputting the following warning for the filter fields component.
WARN: 'tooltipPlacement was deprecated, please use placement instead'
Renaming the attribute is simple; however, this means that Planner must also upgrade ng2-bootstrap to 1.3.3 -- they are still on 1.1.16. I created another PR for that:
fabric8io/fabric8-planner#1119

Deprecation fix

---

src/app/toolbar/toolbar.component.html

There is an extra separator after the filter when actions are not provided. For example, the runtime UI has no action buttons, menus, etc., but a separator is still shown.

Hide extra separator when toolbar actions are not provided

---

src/app/treelist/examples/treelist-example.component.html
src/app/treelist/examples/treelist-example.component.ts
src/app/treelist/treelist.component.html
src/app/treelist/treelist.component.ts

This is for issue #48.
Supported events:
onEvent - Catch-all event that is triggered on every other event that is triggered
onInitialized - Triggers after tree model was created
onMoveNode - This event is fired when drag and dropping a node
onToggle - Triggers when tree node is expanded or collapsed
onUpdateData - Triggers after tree model was updated

Expose underlying angular2-tree-component events

---

src/app/treelist/examples/treelist-example.component.html
src/app/treelist/treelist-item.component.html
src/app/treelist/treelist-item.component.scss
src/app/treelist/treelist-item.component.ts
src/app/treelist/treelist.component.html
src/app/treelist/treelist.component.scss
src/app/treelist/treelist.component.ts

Modified drag and drop highlighting to better mimic the mock-up at: https://redhat.invisionapp.com/share/YV9U2DO2R#/screens/212276939.
Modified the cursor style while dragging; however, I cannot make it appear exactly as shown in the mock-up. Browsers show a cursor based on the drag effect type; copy, move, etc.

fix(treelist): Added styling to mimic dnd mockup

---

src/app/config/action.ts
src/app/config/view.ts
src/app/filters/filter-fields.component.html
src/app/notification/examples/toast-notification-example.component.ts
src/app/notification/examples/toast-notification-list-example.component.ts
src/app/notification/toast-notification.component.html
src/app/notification/toast-notification.component.ts
src/app/toolbar/examples/toolbar-example.component.html
src/app/toolbar/examples/toolbar-example.component.ts
src/app/toolbar/toolbar.component.html
src/app/toolbar/toolbar.component.spec.ts
src/app/toolbar/toolbar.component.ts
src/app/treelist/examples/treelist-example.component.ts

Want to clean up a couple things like inconsistent variable names inherited from various Angular Patternfly components. The new list view follows these naming conventions.

fix: Clean up inconsistent variable names

---

package.json
src/app/treelist/examples/treelist-example.component.ts
src/app/treelist/examples/treelist-example.module.ts
src/app/treelist/treelist-item.component.html
src/app/treelist/treelist-item.component.ts
src/app/treelist/treelist.component.html
src/app/treelist/treelist.component.spec.ts
src/app/treelist/treelist.component.ts
src/app/treelist/treelist.module.ts

Refactored tree list to use angular-tree-component v3.2.4, which is based on Angular 4.
Note that the package name has been renamed from angular2-tree-component to angular-tree-component.

fix(treelist): Upgraded from v2.7.0 to 3.2.4

---

src/app/listview/examples/listview-example.component.html
src/app/listview/examples/listview-example.component.scss
src/app/listview/examples/listview-example.component.ts
src/app/listview/examples/listview-example.module.ts
src/app/listview/listview-config.ts
src/app/listview/listview.component.html
src/app/listview/listview.component.scss

Refactored list view to place column headers on their own row. 
An issue was discovered after adding an info icon to the header. When the user hovers over the icon, a tooltip is displayed, but the first row is unexpectedly highlighted. Moving headers to their own row ensures mouseover/mouseenter events are not fired for the first list view row. 
This update will be used with the list view on the codebases page.

fix(list view): Headers must be on own row

---

package.json

This PR fixes an issue with the build, which appears to be due to package dependencies. 
We started seeing this with the Travis build for patternfly-ng and the solution was to bump the typscript version. 
@sanbornsen reported this with the ngx-widgets repo, which no longer builds.

Error in plugin 'gulp-ngc'

---

src/app/markdown/markdown.component.less

Fix: https://github.com/openshiftio/openshift.io/issues/961
Before this PR:
Now in this PR:

fix(markdown): text and image overflow in markdown

---

src/app/icon/iconmap.ts

Removed class 'color-purple' because it is neither defined anywhere nor being used.
Refer : #113

fix(icon) : added support for icon color

---

src/app/editable/almeditable.directive.ts
src/app/markdown/markdown.component.html
src/app/markdown/markdown.component.ts

Following the GitHub pattern, if a markdown component is empty, clicking on it will make it editable and set focus on it. If the markdown component has text in it, the user needs to click on the edit icon to make it editable.

Set focus on an empty markdown component, when a user clicks on it

---

src/app/slide-out-panel/slide-out-panel.component.less

Update the placement of the slideout panel to account for the fixed navbar. Also adjusts errors in the Less conversion from `em` to `px` when calculated in the browser (this caused placement issues).
fixes https://github.com/openshiftio/openshift.io/issues/1180

fix(panel): fix placement of panel with fixed navbar

---

src/app/markdown/markdown.component.less

fix CSS for markdown edit icon as per VD: https://redhat.invisionapp.com/share/5AFTMT37QDE#/screens/279008732_MarkDown_02

fix(markdown): fix css for markdown as per VD

---

src/app/icon/almicon-test.component.ts
src/app/icon/almicon.directive.spec.ts
src/app/icon/almicon.directive.ts

When any icon type does not exist in our icon map it should go for the default icon type to show the default icon and color. 
It was codded correct, but in the ```else``` part where it actually should take the default color, it was trying to fetch color from ```IconMap[this.iconType].color``` where ```IconMap[this.iconType]``` is undefined.

fix(icon): default icon bug fixed

---

src/app/github-link-area/examples/github-link-area-example.component.html
src/app/github-link-area/examples/github-link-area-example.component.ts
src/app/github-link-area/github-link-area.component.html
src/app/github-link-area/github-link-area.component.ts
src/app/github-link-area/github-link-area.module.ts
src/app/github-link-area/safe.pipe.ts
src/app/markdown/examples/markdown-example.component.ts
src/app/markdown/markdown.component.html
src/app/markdown/markdown.component.spec.ts
src/app/markdown/markdown.component.ts

Adds checkbox support for Markdown.

feat(checkboxes): Added checkbox support for Markdown.

---

README.md
package.json

related to openshiftio/openshift.io#3686
Move angular from `dependencies` to `peerDependencies`.
`npm link --production` must be used to omit installation of `devDependencies` when linking.
Also updated patternfly-ng to align with fabric8-ui because version 0.13.1 did not use `peerDependencies` for angular.

fix(dependencies): use peer dependencies

---

src/app/markdown/markdown.component.html

Changes button to button tag from a div tag. This changes required because we can not disable the div by adding disable attributes to it.

fix(markdown): change actual button to button tag from div tag

---

gulpfile.js
package.json
tsconfig-aot.json
tsconfig.json

Fixed the `ngx-widgets` gulp scripts to add the missing CSS files to the `dist` dir.
Also fixed the `watch` commands to ensure all CSS files and inline HTML templates are updated.

fix(build): fix gulp script for watch and missing css in dist

---

src/app/markdown/markdown.component.spec.ts
src/app/markdown/markdown.component.ts

Fixes: https://github.com/openshiftio/openshift.io/issues/4049
This PR is a part of this PR https://github.com/fabric8-ui/fabric8-planner/pull/2781 in fabric8-ui

fix(markdown): emit event on outside-click if no data changed

---

package.json

With ngx-widgets version 3.1.2(https://github.com/fabric8-ui/ngx-widgets/pull/156) the directory structure changed for published package which caused the following error in planner
```
{ Error: /home/sbudhwar/node_modules/ngx-widgets/index.js: Couldn't find preset "env" relative to directory "/home/sbudhwar/node_modules/ngx-widgets"
Transform function: 
function (context, callback) {
if (!context.js) {
return callback(undefined, false);
}
if (isEs6(context.js.ast)) {
options.filename = context.filename;
log.debug("Transforming %s", options.filename);
try {
context.source = babel.transform(context.source, options).code;
context.js.ast = acorn.parse(context.source, { sourceType: "module" });
return callback(undefined, true);
}
catch (error) {
return callback(error, false);
}
}
else {
return …
```

fix(package.json): add entry point `main` for node packaging

---

src/app/markdown/markdown.component.html
src/app/markdown/markdown.component.ts

This PR is an enhancement over https://github.com/fabric8-ui/ngx-widgets/pull/157
Due to event bubbling the click on the preview-area was getting caught as a click outside the markdown and hence the markdown was not opening in editing mode while clicking on the preview-area.

fix(markdown): handle click event on preview
