fabric8-ui/ngx-widgets

index.ts, src/app/treelist/treelist.component.scss, src/app/treelist/treelist.component.ts, src/app/treelist/treelist.module.ts
Required changes for treelist to run in planner UI, including export all treelist objects and convert styles to string.
=> Need to export TreeListComponent

.gitignore, index.ts, package.json, src/app/pipes/arrayCount.pipe.spec.ts, src/app/pipes/arrayCount.pipe.ts, tsconfig.json, widgets.module.ts
add support for AoT
feat(pipes): add ArrayCount pipe 
fix(build): move transpile-sass step before bundle step
=> AoT, ArrayCount Pipe, Fix to build

src/app/toolbar/toolbar.component.spec.ts, src/app/treelist/treelist.component.spec.ts
Inadvertently included a new class, which broke the unit test
=> Fixed unit tests

config/webpack.demo.js, src/app/filters/examples/filter-example.module.ts, src/app/filters/filter.component.spec.ts, src/app/filters/filters.module.ts, src/app/sort/examples/sort-example.component.ts, src/app/sort/sort.component.spec.ts, src/app/toolbar/examples/toolbar-example.component.ts, src/app/toolbar/examples/toolbar-example.module.ts, src/app/toolbar/toolbar.component.spec.ts, src/app/treelist/examples/treelist-example.component.ts, tsconfig.json
This fixes the tests and demo after the recent package version bumps.
=> Fix for the tests and demo

index.ts
Need to export this object for use in planner
=> Toolbar config

src/app/filters/filter-results.component.ts, src/app/notification/notification.ts
Renaming a "shadowed" variable in filter and a line with 100+ chars -- to silence build warnings.
=> Fixed shadowed variable in filter

index.ts, src/app/config/action.ts, src/app/notification/examples/toast-notification-example.component.ts, src/app/notification/examples/toast-notification-list-example.component.ts, src/app/notification/notification.ts, widgets.module.ts
* Add an optional callback to the Action. When creating an action the user can optionally specify a callback they would like run
* Add optional callbacks to toast notification list demo
* Export all of notifications
=> feat(notification): add callback to Action

src/app/filters/filter-config.ts
Filter results and other count types should be optional.
=> fix(filter): Counts should be an optional type

index.ts, src/app/notification/examples/notification-example.module.ts, src/app/notification/examples/toast-notification-example.component.ts, src/app/notification/examples/toast-notification-list-example.component.html, src/app/notification/examples/toast-notification-list-example.component.ts, src/app/notification/notification-event.ts, src/app/notification/notification.module.ts, src/app/notification/notification.service.ts, src/app/notification/notification.ts, src/app/notification/toast-notification-list.component.html, src/app/notification/toast-notification-list.component.ts, src/app/notification/toast-notification.component.ts
Created a notification service for the notification list component. This supports the missing timeout and persistence functionality Pete is looking for.
=> Notification service

src/app/notification/examples/notification-example.module.ts, src/app/notification/examples/notification-example.service.ts, src/app/notification/notification.service.ts
Set verbose default to false and added example showing how to override notification service defaults
=> Example showing how to override notification service defaults

config/karma.conf.js, config/webpack.test.js, tsconfig-test.json
Sets karma debug to false (drops 15s)
Removes extra sourcemaps
Optimizes tsconfig settings for test run
=> fix(tests): optimize test runs

index.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/home/home.component.html, src/app/listview/emptystate-config.ts, src/app/listview/examples/listview-example-routing.module.ts, src/app/listview/examples/listview-example.component.html, src/app/listview/examples/listview-example.component.scss, src/app/listview/examples/listview-example.component.ts, src/app/listview/examples/listview-example.module.ts, src/app/listview/listview-actions.component.html, src/app/listview/listview-actions.component.scss, src/app/listview/listview-actions.component.ts, src/app/listview/listview-config.ts, src/app/listview/listview-event.ts, src/app/listview/listview.component.html, src/app/listview/listview.component.scss, src/app/listview/listview.component.spec.ts, src/app/listview/listview.component.ts, src/app/listview/listview.module.ts
Note there are no action buttons/kebabs, drag and drop functionality, or unit tests. However, this is enough to use the list view component on the new codebases page.
=> feat(list view): Initial list view component implementation.

index.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/home/home.component.html, src/app/slide-out-panel/examples/slide-out-example-routing.module.ts, src/app/slide-out-panel/examples/slide-out-example.component.html, src/app/slide-out-panel/examples/slide-out-example.component.scss, src/app/slide-out-panel/examples/slide-out-example.component.ts, src/app/slide-out-panel/examples/slide-out-example.module.ts, src/app/slide-out-panel/slide-out-panel.component.html, src/app/slide-out-panel/slide-out-panel.component.scss, src/app/slide-out-panel/slide-out-panel.component.spec.ts, src/app/slide-out-panel/slide-out-panel.component.ts, src/app/slide-out-panel/slide-out-panel.module.ts, src/assets/stylesheets/_custom-variables.scss
small slide-out component based on the 
component in the planner
includes
- example
- tests
=> Slide out panel component

index.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/home/home.component.html, src/app/remainingchars/examples/remainingchars-example-routing.module.ts, src/app/remainingchars/examples/remainingchars-example.component.html, src/app/remainingchars/examples/remainingchars-example.component.scss, src/app/remainingchars/examples/remainingchars-example.component.ts, src/app/remainingchars/examples/remainingchars-example.module.ts, src/app/remainingchars/remainingchars-config.ts, src/app/remainingchars/remainingchars.component.html, src/app/remainingchars/remainingchars.component.scss, src/app/remainingchars/remainingchars.component.spec.ts, src/app/remainingchars/remainingchars.component.ts, src/app/remainingchars/remainingchars.module.ts
Ported the "remaining characters count" component from Angular Patternfly. This specialized textarea will be used for the user's bio on the update profile page of fabric8-ui, per mockups.
=> feat(): Added remaining chars component

src/app/listview/listview.component.scss, src/app/toolbar/toolbar.component.scss
update the list view and toolbar components for responsive usage. syncs with PR https://github.com/fabric8io/fabric8-ui/pull/1575
=> fix(responsive): update for responsive use

src/app/markdown/examples/markdown-example.component.html, src/app/markdown/examples/markdown-example.component.ts, src/app/markdown/markdown.component.ts
Fixing OSIO issue 1443 - 
https://openshift.io/openshiftio/openshiftio/plan/detail/3a331aa3-6423-4fd7-85e4-95d7932b168c
=> fix(markdown): Fixed markdown component with undefined values.

release.groovy
Ensuring the correct branch is released
=> fix(build): add switch to git master prior to build release

src/app/github-link-area/github-link-area.component.html, src/app/markdown/examples/markdown-example.component.ts, src/app/markdown/markdown.component.less
As per Patternfly, Border colour and boxshadows has been updated to markdown field
=> Add border/ boxshadow to markdown component as per Patternfly

src/app/icon/iconmap.ts
Please refer: #113 and openshiftio/openshift.io#325
=> fix(icon) : WI status 'new' icon changed

src/app/infinitescroll/infinitescroll.directive.ts
Fix - https://openshift.io/openshiftio/openshiftio/plan/detail/1728
=> fix(infinitescroll): Move all ngOnInit operations to ngDoCheck

src/app/markdown/markdown.component.html, src/app/markdown/markdown.component.ts
=> view show more/less when content is long

src/app/infinitescroll/infinitescroll.directive.ts
This reverts commit 5c51bede324e7f12623b4ea8ba1fa6f69f504811.
fixes https://github.com/openshiftio/openshift.io/issues/2378
=> Revert "fix(infinitescroll): Move all ngOnInit operations to ngDoCheck"

src/app/markdown/markdown.component.html, src/app/markdown/markdown.component.less
https://openshift.io/openshiftio/openshiftio/plan/detail/1970
=> fix(markdown): fix cosmetic issues in markdown

src/app/markdown/markdown.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4207 and https://github.com/openshiftio/openshift.io/issues/3894
=> fix(markdown): Ensure fieldEmpty get correct value on chrome and firefox
